#ifndef SKYNETMINI_CONTROLLER2__VISIBILITY_CONTROL_H_
#define SKYNETMINI_CONTROLLER2__VISIBILITY_CONTROL_H_
#if defined _WIN32 || defined __CYGWIN__
  #ifdef __GNUC__
    #define SKYNETMINI_CONTROLLER2_EXPORT __attribute__ ((dllexport))
    #define SKYNETMINI_CONTROLLER2_IMPORT __attribute__ ((dllimport))
  #else
    #define SKYNETMINI_CONTROLLER2_EXPORT __declspec(dllexport)
    #define SKYNETMINI_CONTROLLER2_IMPORT __declspec(dllimport)
  #endif
  #ifdef SKYNETMINI_CONTROLLER2_BUILDING_LIBRARY
    #define SKYNETMINI_CONTROLLER2_PUBLIC SKYNETMINI_CONTROLLER2_EXPORT
  #else
    #define SKYNETMINI_CONTROLLER2_PUBLIC SKYNETMINI_CONTROLLER2_IMPORT
  #endif
  #define SKYNETMINI_CONTROLLER2_PUBLIC_TYPE SKYNETMINI_CONTROLLER2_PUBLIC
  #define SKYNETMINI_CONTROLLER2_LOCAL
#else
  #define SKYNETMINI_CONTROLLER2_EXPORT __attribute__ ((visibility("default")))
  #define SKYNETMINI_CONTROLLER2_IMPORT
  #if __GNUC__ >= 4
    #define SKYNETMINI_CONTROLLER2_PUBLIC __attribute__ ((visibility("default")))
    #define SKYNETMINI_CONTROLLER2_LOCAL  __attribute__ ((visibility("hidden")))
  #else
    #define SKYNETMINI_CONTROLLER2_PUBLIC
    #define SKYNETMINI_CONTROLLER2_LOCAL
  #endif
  #define SKYNETMINI_CONTROLLER2_PUBLIC_TYPE
#endif
#endif  // SKYNETMINI_CONTROLLER2__VISIBILITY_CONTROL_H_
// Generated 18-Nov-2024 04:28:51
// Copyright 2019-2020 The MathWorks, Inc.
